blank_issues_enabled: false
contact_links:
  - name: Questions and ideas
    url: https://github.com/thatdragonlegacyauthor/dlttrpg2.0/issues
    about: Use a Feature request or Task template to start a conversation.
