name: "Feature request"
description: "Suggest new rules, content, or improvements"
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or opportunity
      description: What need does this address?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the change and where it should live (system/world/characters/campaign).
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context
