name: "Task"
description: "A concrete piece of work"
labels: ["task"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What needs to be done?
      placeholder: Short description of the task.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list of what must be true to consider this done.
      placeholder: |
        - [ ] condition 1
        - [ ] condition 2
